export enum EInedibleFlags {
  APPLE='APPLE',
  VEGAN ='VEGAN',
  VEGETARIAN = 'VEGETARIAN',
  GLUTEN = 'GLUTEN',
  PESCETARIAN ='PESCETARIAN',
  LACTOSE = 'LACTOSE',
  UNCOOKED_ROOT_VEGGIES='UNCOOKED_ROOT_VEGGIES',
  CITRUS_FRUIT='CITRUS_FRUIT',
  WALNUTS='WALNUTS',
  MUSHROOM='MUSHROOM',
}
